#!/bin/bash

set -e

openwisp-qa-check --skip-checkmigrations

# test sphinx docs
mkdir -p docs/source/_static
make -C docs html

PYTHON_VERSION=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
if [[ $PYTHON_VERSION != 3.6 ]]; then
    # check for broken links
    # remove condition when 3.6 is dropped
    python -m http.server 8001 -d docs/build/html/ &>/dev/null &
    pid=$!
    sleep 4
    pylinkvalidate.py http://localhost:8001/
    kill "${pid}" 2> /dev/null || true
fi
